services:
  frankenphp:
    image: dunglas/frankenphp
    container_name: web
    restart: always
    network_mode: bridge
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/:/etc/caddy/
      - ./html:/app/public

  mariadb:
    image: mariadb:10.11.10-ubi
    container_name: mariadb
    restart: always
    network_mode: bridge
    volumes:
      - ./mysql:/var/lib/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: webuser
      MYSQL_PASSWORD: webpassword

  redis:
    image: redis
    container_name: redis
    restart: always
    network_mode: bridge
    volumes:
      - ./redis:/data
