services:
  frankenphp:
    image: dunglas/frankenphp:php8.2-alpine
    container_name: web
    restart: always
    network_mode: bridge
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/:/etc/caddy/
      - ./html:/app/public

  mariadb:
    image: linuxserver/mariadb:10.11.10
    container_name: mariadb
    restart: always
    network_mode: bridge
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword

  redis:
    image: redis
    container_name: redis
    restart: always
    network_mode: bridge
    volumes:
      - ./redis:/data
